from dotenv import load_dotenv
import os

load_dotenv()

ACCESS_TOKEN = os.getenv("ACCESS_TOKEN")
PHONE_NUMBER_ID = os.getenv("PHONE_NUMBER_ID")
VERIFY_TOKEN = os.getenv("VERIFY_TOKEN")

GOOGLE_CALENDAR_ID = os.getenv("GOOGLE_CALENDAR_ID")
GOOGLE_SERVICE_ACCOUNT_FILE = os.getenv("GOOGLE_SERVICE_ACCOUNT_FILE", "service_account.json")
GOOGLE_SERVICE_ACCOUNT_JSON = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON")

REMINDER_JOB_SECRET = os.getenv("REMINDER_JOB_SECRET")

USE_TEMPLATE_REMINDERS = os.getenv("USE_TEMPLATE_REMINDERS", "false").lower() == "true"
WHATSAPP_REMINDER_TEMPLATE_NAME = os.getenv(
    "WHATSAPP_REMINDER_TEMPLATE_NAME",
    "appointment_reminder_es_mx"
)
WHATSAPP_TEMPLATE_LANGUAGE = os.getenv("WHATSAPP_TEMPLATE_LANGUAGE", "es_MX")